# Generated by Django 5.1.6 on 2025-03-11 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mesajlar', '0001_initial'),
    ]

    operations = [
    ]
