# Generated by Django 5.1.6 on 2025-03-06 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teklifler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teklif',
            name='durum',
            field=models.CharField(choices=[('BEKLEMEDE', 'Beklemede'), ('ONAYLANDI', 'Onaylandı'), ('REDDEDILDI', 'Reddedildi'), ('REVIZYON', 'Revizyon')], default='BEKLEMEDE', max_length=20),
        ),
    ]
