# Generated by Django 5.1.6 on 2025-03-14 14:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bildirim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip', models.CharField(choices=[('ONAY', 'Onay'), ('RED', 'Red'), ('REVIZYON', 'Revizyon')], max_length=20)),
                ('mesaj', models.TextField()),
                ('okundu', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Bildirim',
                'verbose_name_plural': 'Bildirimler',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Musteri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_soyad', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefon', models.CharField(max_length=20)),
                ('firma_adi', models.CharField(blank=True, max_length=100)),
                ('adres', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Müşteri',
                'verbose_name_plural': 'Müşteriler',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_firma_sahibi', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TeklifAnalitik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarih', models.DateField(auto_now_add=True)),
                ('toplam_teklif', models.IntegerField(default=0)),
                ('onaylanan_teklif', models.IntegerField(default=0)),
                ('reddedilen_teklif', models.IntegerField(default=0)),
                ('ortalama_yanit_suresi', models.DurationField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Urun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100)),
                ('aciklama', models.TextField()),
                ('fiyat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('kategori', models.CharField(max_length=50)),
            ],
        ),
    ]
