# Generated by Django 5.1.6 on 2025-03-07 23:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('musteri', '0001_initial'),
        ('teklifler', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bildirim',
            name='teklif',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teklifler.teklif'),
        ),
        migrations.AddField(
            model_name='musteri',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bildirim',
            name='musteri',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musteri.musteri'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
